### PR TITLE
Calculate callability using bedtools genomecov

### PR DESCRIPTION
**Pull request by mlaszloffy**
Tests cases imported from mutect callability

### CODE REVIEW

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Comment by mlaszloffy** [comment]
retest this please

**Review by alexjfortuna — APPROVED** [review]

**Review by torchij — APPROVED** [review]

**Pull request merged**
